name: CI/CD

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
    paths-ignore:
      - "kubernetes/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  update-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: LeadcodeDev/voicehandler
          ref: main
  build-and-push:
    needs: [update-chart]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract short SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/leadcodedev/voicehandler:${{ env.sha }}
          provenance: false
