name: CI/CD

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
    paths-ignore:
      - "kubernetes/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  update-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: LeadcodeDev/voicehandler
          ref: main
  build-and-push:
    needs: [update-chart]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract short SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Login to Scaleway container registry
        uses: docker/login-action@v3
        with:
          # URL de la registry Scaleway pour la région Paris
          registry: rg.fr-par.scw.cloud/natalia-private-registry
          # Le username pour l'authentification par token est 'nologin'
          username: ${{ secrets.CI_REGISTRY_USER }}
          # Le mot de passe est la clé secrète stockée dans les secrets GitHub
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Mettez à jour le tag pour correspondre à votre registry Scaleway
          tags: rg.fr-par.scw.cloud/natalia-private-registry/voicehandler-rs:${{ env.sha }}
          provenance: false
